# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rbcx.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rbcx.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\nrbcx.proto\"I\n\nStmMessage\x12\x1b\n\x11\x62uttonsStatusMask\x18\x01 \x01(\rH\x00\x12\x13\n\tbatteryMv\x18\x02 \x01(\rH\x00\x42\t\n\x07payload\"W\n\nEspMessage\x12$\n\nmotorPower\x18\x01 \x01(\x0b\x32\x0e.SetMotorPowerH\x00\x12\x18\n\x0eledsStatusMask\x18\x02 \x01(\rH\x00\x42\t\n\x07payload\"/\n\rSetMotorPower\x12\x0f\n\x07motorId\x18\x01 \x01(\r\x12\r\n\x05power\x18\x02 \x01(\rb\x06proto3'
)




_STMMESSAGE = _descriptor.Descriptor(
  name='StmMessage',
  full_name='StmMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='buttonsStatusMask', full_name='StmMessage.buttonsStatusMask', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batteryMv', full_name='StmMessage.batteryMv', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='StmMessage.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=14,
  serialized_end=87,
)


_ESPMESSAGE = _descriptor.Descriptor(
  name='EspMessage',
  full_name='EspMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motorPower', full_name='EspMessage.motorPower', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ledsStatusMask', full_name='EspMessage.ledsStatusMask', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='EspMessage.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=89,
  serialized_end=176,
)


_SETMOTORPOWER = _descriptor.Descriptor(
  name='SetMotorPower',
  full_name='SetMotorPower',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motorId', full_name='SetMotorPower.motorId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='power', full_name='SetMotorPower.power', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=225,
)

_STMMESSAGE.oneofs_by_name['payload'].fields.append(
  _STMMESSAGE.fields_by_name['buttonsStatusMask'])
_STMMESSAGE.fields_by_name['buttonsStatusMask'].containing_oneof = _STMMESSAGE.oneofs_by_name['payload']
_STMMESSAGE.oneofs_by_name['payload'].fields.append(
  _STMMESSAGE.fields_by_name['batteryMv'])
_STMMESSAGE.fields_by_name['batteryMv'].containing_oneof = _STMMESSAGE.oneofs_by_name['payload']
_ESPMESSAGE.fields_by_name['motorPower'].message_type = _SETMOTORPOWER
_ESPMESSAGE.oneofs_by_name['payload'].fields.append(
  _ESPMESSAGE.fields_by_name['motorPower'])
_ESPMESSAGE.fields_by_name['motorPower'].containing_oneof = _ESPMESSAGE.oneofs_by_name['payload']
_ESPMESSAGE.oneofs_by_name['payload'].fields.append(
  _ESPMESSAGE.fields_by_name['ledsStatusMask'])
_ESPMESSAGE.fields_by_name['ledsStatusMask'].containing_oneof = _ESPMESSAGE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['StmMessage'] = _STMMESSAGE
DESCRIPTOR.message_types_by_name['EspMessage'] = _ESPMESSAGE
DESCRIPTOR.message_types_by_name['SetMotorPower'] = _SETMOTORPOWER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StmMessage = _reflection.GeneratedProtocolMessageType('StmMessage', (_message.Message,), {
  'DESCRIPTOR' : _STMMESSAGE,
  '__module__' : 'rbcx_pb2'
  # @@protoc_insertion_point(class_scope:StmMessage)
  })
_sym_db.RegisterMessage(StmMessage)

EspMessage = _reflection.GeneratedProtocolMessageType('EspMessage', (_message.Message,), {
  'DESCRIPTOR' : _ESPMESSAGE,
  '__module__' : 'rbcx_pb2'
  # @@protoc_insertion_point(class_scope:EspMessage)
  })
_sym_db.RegisterMessage(EspMessage)

SetMotorPower = _reflection.GeneratedProtocolMessageType('SetMotorPower', (_message.Message,), {
  'DESCRIPTOR' : _SETMOTORPOWER,
  '__module__' : 'rbcx_pb2'
  # @@protoc_insertion_point(class_scope:SetMotorPower)
  })
_sym_db.RegisterMessage(SetMotorPower)


# @@protoc_insertion_point(module_scope)
