/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "rbcx.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CoprocReq, CoprocReq, AUTO)


PB_BIND(CoprocReq_SetLeds, CoprocReq_SetLeds, AUTO)


PB_BIND(CoprocReq_GetButtons, CoprocReq_GetButtons, AUTO)


PB_BIND(CoprocStat, CoprocStat, AUTO)


PB_BIND(CoprocStat_LedsStat, CoprocStat_LedsStat, AUTO)


PB_BIND(CoprocStat_ButtonsStat, CoprocStat_ButtonsStat, AUTO)





