/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3 */

#include "rbcx.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(None, None, AUTO)


PB_BIND(RegCoefs, RegCoefs, AUTO)


PB_BIND(MotorConfig, MotorConfig, AUTO)


PB_BIND(CoprocReq, CoprocReq, AUTO)


PB_BIND(CoprocReq_SetLeds, CoprocReq_SetLeds, AUTO)


PB_BIND(CoprocReq_GetButtons, CoprocReq_GetButtons, AUTO)


PB_BIND(CoprocReq_SetStupidServo, CoprocReq_SetStupidServo, AUTO)


PB_BIND(CoprocReq_UltrasoundReq, CoprocReq_UltrasoundReq, AUTO)


PB_BIND(CoprocReq_MotorReq, CoprocReq_MotorReq, AUTO)


PB_BIND(CoprocReq_MotorReq_SetPosition, CoprocReq_MotorReq_SetPosition, AUTO)


PB_BIND(CoprocReq_BuzzerReq, CoprocReq_BuzzerReq, AUTO)


PB_BIND(CoprocReq_CalibratePower, CoprocReq_CalibratePower, AUTO)


PB_BIND(CoprocStat, CoprocStat, AUTO)


PB_BIND(CoprocStat_ButtonsStat, CoprocStat_ButtonsStat, AUTO)


PB_BIND(CoprocStat_UltrasoundStat, CoprocStat_UltrasoundStat, AUTO)


PB_BIND(CoprocStat_MotorStat, CoprocStat_MotorStat, AUTO)


PB_BIND(CoprocStat_PowerAdcStat, CoprocStat_PowerAdcStat, AUTO)


PB_BIND(CoprocStat_VersionStat, CoprocStat_VersionStat, AUTO)






