/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_RBCX_PB_H_INCLUDED
#define PB_RBCX_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _CoprocRequest_GetButtonsState {
    char dummy_field;
} CoprocRequest_GetButtonsState;

typedef struct _CoprocStatus_LedsStatus {
    char dummy_field;
} CoprocStatus_LedsStatus;

typedef struct _CoprocRequest_SetLeds {
    uint32_t ledsOn;
} CoprocRequest_SetLeds;

typedef struct _CoprocStatus_ButtonsStatus {
    uint32_t buttonsPressed;
} CoprocStatus_ButtonsStatus;

typedef struct _CoprocRequest {
    pb_size_t which_payload;
    union {
        CoprocRequest_SetLeds setLeds;
        CoprocRequest_GetButtonsState getButtonsState;
    } payload;
} CoprocRequest;

typedef struct _CoprocStatus {
    pb_size_t which_payload;
    union {
        CoprocStatus_LedsStatus ledsStatus;
        CoprocStatus_ButtonsStatus buttonsStatus;
    } payload;
} CoprocStatus;


/* Initializer values for message structs */
#define CoprocRequest_init_default               {0, {CoprocRequest_SetLeds_init_default}}
#define CoprocRequest_SetLeds_init_default       {0}
#define CoprocRequest_GetButtonsState_init_default {0}
#define CoprocStatus_init_default                {0, {CoprocStatus_LedsStatus_init_default}}
#define CoprocStatus_LedsStatus_init_default     {0}
#define CoprocStatus_ButtonsStatus_init_default  {0}
#define CoprocRequest_init_zero                  {0, {CoprocRequest_SetLeds_init_zero}}
#define CoprocRequest_SetLeds_init_zero          {0}
#define CoprocRequest_GetButtonsState_init_zero  {0}
#define CoprocStatus_init_zero                   {0, {CoprocStatus_LedsStatus_init_zero}}
#define CoprocStatus_LedsStatus_init_zero        {0}
#define CoprocStatus_ButtonsStatus_init_zero     {0}

/* Field tags (for use in manual encoding/decoding) */
#define CoprocRequest_SetLeds_ledsOn_tag         1
#define CoprocStatus_ButtonsStatus_buttonsPressed_tag 1
#define CoprocRequest_setLeds_tag                4
#define CoprocRequest_getButtonsState_tag        5
#define CoprocStatus_ledsStatus_tag              4
#define CoprocStatus_buttonsStatus_tag           5

/* Struct field encoding specification for nanopb */
#define CoprocRequest_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,setLeds,payload.setLeds),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,getButtonsState,payload.getButtonsState),   5)
#define CoprocRequest_CALLBACK NULL
#define CoprocRequest_DEFAULT NULL
#define CoprocRequest_payload_setLeds_MSGTYPE CoprocRequest_SetLeds
#define CoprocRequest_payload_getButtonsState_MSGTYPE CoprocRequest_GetButtonsState

#define CoprocRequest_SetLeds_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ledsOn,            1)
#define CoprocRequest_SetLeds_CALLBACK NULL
#define CoprocRequest_SetLeds_DEFAULT NULL

#define CoprocRequest_GetButtonsState_FIELDLIST(X, a) \

#define CoprocRequest_GetButtonsState_CALLBACK NULL
#define CoprocRequest_GetButtonsState_DEFAULT NULL

#define CoprocStatus_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ledsStatus,payload.ledsStatus),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,buttonsStatus,payload.buttonsStatus),   5)
#define CoprocStatus_CALLBACK NULL
#define CoprocStatus_DEFAULT NULL
#define CoprocStatus_payload_ledsStatus_MSGTYPE CoprocStatus_LedsStatus
#define CoprocStatus_payload_buttonsStatus_MSGTYPE CoprocStatus_ButtonsStatus

#define CoprocStatus_LedsStatus_FIELDLIST(X, a) \

#define CoprocStatus_LedsStatus_CALLBACK NULL
#define CoprocStatus_LedsStatus_DEFAULT NULL

#define CoprocStatus_ButtonsStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   buttonsPressed,    1)
#define CoprocStatus_ButtonsStatus_CALLBACK NULL
#define CoprocStatus_ButtonsStatus_DEFAULT NULL

extern const pb_msgdesc_t CoprocRequest_msg;
extern const pb_msgdesc_t CoprocRequest_SetLeds_msg;
extern const pb_msgdesc_t CoprocRequest_GetButtonsState_msg;
extern const pb_msgdesc_t CoprocStatus_msg;
extern const pb_msgdesc_t CoprocStatus_LedsStatus_msg;
extern const pb_msgdesc_t CoprocStatus_ButtonsStatus_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define CoprocRequest_fields &CoprocRequest_msg
#define CoprocRequest_SetLeds_fields &CoprocRequest_SetLeds_msg
#define CoprocRequest_GetButtonsState_fields &CoprocRequest_GetButtonsState_msg
#define CoprocStatus_fields &CoprocStatus_msg
#define CoprocStatus_LedsStatus_fields &CoprocStatus_LedsStatus_msg
#define CoprocStatus_ButtonsStatus_fields &CoprocStatus_ButtonsStatus_msg

/* Maximum encoded size of messages (where known) */
#define CoprocRequest_size                       8
#define CoprocRequest_SetLeds_size               6
#define CoprocRequest_GetButtonsState_size       0
#define CoprocStatus_size                        8
#define CoprocStatus_LedsStatus_size             0
#define CoprocStatus_ButtonsStatus_size          6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
